### ISSUE TITLE
Umap information of the individual cardiac region?

### ISSUE THREAD

**Issue by ShaowenJ** [cartal/HCA_Heart#3]
Dear HCA project contributors,

First, I want like to express my gratitude and appreciation for your work and willingness to share the data in such a well-organized way! 

I downloaded the h5ad from your website https://www.heartcellatlas.org/#CardiacRegions and load it in R via Seurat. (Sorry, I am a R guy). But the object seems to have only the original whole Umap information. 
So I want to know if I can have a h5ad object that has stored the umap for individual cardiac region? Especially interested in the vascular one.

Thanks!

**Comment by ShaowenJ** [comment]
I guess the one I cannot have the re-analysis Umap object is the "Heart Vascular" one, the Immune one has the new Umap.
![image](https://user-images.githubusercontent.com/30546732/116506413-c9ba1e00-a8ef-11eb-9515-61201cb627d4.png)

**Comment by mitraclip** [comment]
Hi Shaowen,  I am also a R guy. I want to ask a question: how do you transform this h5ad file into the seurat object ? Since I have downloaded this file and read it by function "h5read" supported by package rhdf5. But I found, different with the h5 file generated by 10x Cellranger, the transformed file is a list rather than a dgcMatrix
![image](https://user-images.githubusercontent.com/76574724/125379558-4e7ee900-e3c3-11eb-91c1-74ccd1e1ff0e.png)

**Comment by ShaowenJ** [comment]
@mitraclip Hi yuxing,
You can transform the h5ad to seurat object based on Seurat's protocol. 
https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html
If you have any issues, you can look into their githubs

**Comment by mitraclip** [comment]
@Lesdormis  Thank you!

**Comment by cartal** [comment]
Hi guys, I'm terribly sorry that this issue has gone astray and I haven't got back to you. 

First of all, I do strongly recommend to reproduce the analyses using the `scanpy` workflow in this repo, because we know `Seurat` does not support our analyses, and therefore reproducibility fails. However, if you really have to use `Seurat`, you can use [`sceasy`](https://github.com/cellgeni/sceasy).

I will update the object with the right UMAP coordinates in the website.  Thanks!

**Comment by ShaowenJ** [comment]
Thanks!
